# Generated by Django 2.1.1 on 2018-10-24 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliaceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAppliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Appliance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Category')),
            ],
        ),
        migrations.AddField(
            model_name='orderappliances',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Style'),
        ),
        migrations.AddField(
            model_name='appliancestyle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Style'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Brand'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Category'),
        ),
        migrations.AddField(
            model_name='appliacefeature',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Appliance'),
        ),
        migrations.AddField(
            model_name='appliacefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.Feature'),
        ),
    ]
